# Using the 101+45+15 samples.

## Used libraries

In [1]:
import pandas as pd
from pathlib import Path
import re
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

## Read the PKL files:

In [2]:
d101 = pd.read_pickle('../../results/dataframe_spectrum_thickness_101.pkl')
d45 = pd.read_pickle('../../results/dataframe_spectrum_thickness_45.pkl')
d15 = pd.read_pickle('../../results/dataframe_spectrum_thickness_15.pkl')
d101.shape, d45.shape, d15.shape

((101, 6), (45, 5), (15, 5))

In [3]:
d101.head()

,Nombre,Nombre-Arc,Espesor,Error,Error Porcentual,Espectro
0,ANZO32,ANZO32M,91.223787,12.300000,10.000000,"[[[0.071], [0.058], [0.055999], [0.08], [0.055..."
1,ANZO01-1,ANZO011M,141.565084,18.100000,10.925087,"[[[0.037], [0.078], [0.045], [0.092], [0.049],..."
2,ANZO30,ANZO30M,167.256504,21.600000,10.256410,"[[[0.006999], [0.102], [0.029], [0.08], [0.035..."
3,ANZO35,ANZO35M,167.777276,21.100000,9.990530,"[[[0.066], [0.097], [0.023], [0.078], [0.047],..."
4,AZO3Min2,AZO3MI2M,224.029336,8.740362,3.166683,"[[[0.063], [0.091], [0.024], [0.066], [0.063],..."

In [4]:
d45['Nombre'] = d45['Nombre-Arc']

In [5]:
d45.head()

,Nombre-Arc,Espesor,Error,Error Porcentual,Espectro,Nombre
0,ANZO49M,740.366097,81.504077,9.358604,"[[[0.114], [0.118], [0.077], [0.076], [0.068],...",ANZO49M
1,ANZO491M,496.334776,52.884180,8.967330,"[[[0.058], [0.089], [0.055999], [0.095], [0.07...",ANZO491M
2,ANZO492M,642.692876,67.507986,8.901755,"[[[0.053], [0.147], [0.066], [0.104], [0.06999...",ANZO492M
3,ANZO493M,680.180713,100.974310,12.597252,"[[[0.015], [0.084], [0.021], [0.037], [0.028],...",ANZO493M
4,ANZO494M,709.578753,70.921047,8.489179,"[[[0.034], [0.101], [0.035], [0.067], [0.032],...",ANZO494M

In [6]:
d15['Nombre'] = d15['Nombre-Arc']

In [7]:
d15.head()

,Nombre-Arc,Espesor,Error,Error Porcentual,Espectro,Nombre
0,ANZO67M,511.851359,129.99,21.393305,"[[[0.032], [0.106], [0.011], [0.05], [0.032], ...",ANZO67M
1,ANZO671M,445.756709,90.17,16.966150,"[[[0.074], [0.096], [0.047], [0.057], [0.06999...",ANZO671M
2,ANZO672M,433.605361,75.50,14.590218,"[[[0.114], [0.12], [0.048], [0.076], [0.064], ...",ANZO672M
3,ANZO673M,516.390756,133.60,21.799788,"[[[0.125], [0.15], [0.049], [0.088], [0.074], ...",ANZO673M
4,ANZO674M,502.937478,119.26,19.964845,"[[[0.068], [0.094], [0.029], [0.066], [0.028],...",ANZO674M

In [8]:
data = pd.concat([d101, d45, d15]).reset_index(drop = True)
data.shape

(161, 6)

In [9]:
data.head(10)

,Nombre,Nombre-Arc,Espesor,Error,Error Porcentual,Espectro
0,ANZO32,ANZO32M,91.223787,12.300000,10.000000,"[[[0.071], [0.058], [0.055999], [0.08], [0.055..."
1,ANZO01-1,ANZO011M,141.565084,18.100000,10.925087,"[[[0.037], [0.078], [0.045], [0.092], [0.049],..."
2,ANZO30,ANZO30M,167.256504,21.600000,10.256410,"[[[0.006999], [0.102], [0.029], [0.08], [0.035..."
3,ANZO35,ANZO35M,167.777276,21.100000,9.990530,"[[[0.066], [0.097], [0.023], [0.078], [0.047],..."
4,AZO3Min2,AZO3MI2M,224.029336,8.740362,3.166683,"[[[0.063], [0.091], [0.024], [0.066], [0.063],..."
5,AZO3Min,AZO3MINM,224.897289,14.052483,5.072915,"[[[0.071], [0.101], [0.002], [0.084], [0.04], ..."
6,AZO3Min3,AZO3MI3M,228.881195,7.236276,2.569700,"[[[0.072], [0.122], [0.049], [0.069999], [0.04..."
7,ANZO01-2,ANZO012M,246.587444,30.200000,10.789327,"[[[0.064], [0.063], [0.039], [0.083], [0.034],..."
8,ANZO31,ANZO31M,301.355303,74.230000,20.331416,"[[[0.055], [0.116], [0.044], [0.072], [0.076],..."
9,AZO5X,AZO5XM,337.635755,95.608096,23.496706,"[[[0.02], [0.098], [0.054], [0.079], [0.036], ..."

In [10]:
data.to_pickle('../../results/dataframe_spectrum_thickness_161.pkl')